spring:
  servlet:
    multipart:
      max-file-size: 20MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.czarea.zsah
  global-config:
    db-config:
      id-type: auto
      field-strategy: default
      logic-delete-value: 1
      logic-not-delete-value: 0
      capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazyLoadingEnabled: true
    jdbcTypeForNull: null
    multipleResultSetsEnabled: true
